# Generated by Django 3.2.9 on 2024-01-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20240127_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
