# Generated by Django 3.2.9 on 2024-01-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('telefone_secundario', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField()),
                ('plano_saude', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
            ],
        ),
    ]
