# Generated by Django 3.2.9 on 2024-02-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_alter_paciente_plano_saude'),
        ('funcionarios', '0004_alter_cargo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('concluída', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.profissionalsaude')),
            ],
        ),
    ]
