# Generated by Django 3.2.9 on 2024-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('concluída', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
    ]
